### ISSUE TITLE
Right Click is not working after dragging one component

### ISSUE THREAD

**Issue by mcmld** [rozek/svelte-agnostic-draggable#3]
Sample Code is from the repo:
https://svelte.dev/repl/91db405809614aa6943ce7fbac10664f?version=3.49.0

you can still right-click on the page when the code started but when you tried the drag feature, it will not work anymore. this happens for almost all repo I tried in the readme link. same thing when I applied on our project

**Comment by julianlaibach** [comment]
Same issue here! Is there anything we can do about that?

**Comment by rozek** [comment]
I'll check that - but please, give me time until the beginning of march as I currently don't have access to my desktop...

**Comment by rozek** [comment]
I can confirm the problem - even with the latest version of [agnostic-draggable](https://github.com/marcospont/agnostic-draggable) - but since "svelte-agnostic-draggable" is just a small wrapper around that module, you should better open an issue there for this problem.

Just tell me when the issue is solved and I will rebuild a new version
